# Generated by Django 2.2.6 on 2019-10-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
        migrations.AlterModelTable(
            name='idea',
            table='Idea',
        ),
        migrations.AlterModelTable(
            name='inversion',
            table='Inversion',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
