# Generated by Django 2.2.6 on 2019-10-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0002_auto_20191005_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saldo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
