# Generated by Django 2.2.6 on 2019-10-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0003_auto_20191005_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='imagen',
            field=models.ImageField(upload_to='imagenesIdeas/'),
        ),
    ]
