# Generated by Django 2.2.6 on 2019-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0005_user_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='fecha_limite',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='fecha_publicada',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='fecha_inversion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
