# Generated by Django 2.2.6 on 2019-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0006_auto_20191023_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='fecha_reembolso',
            field=models.DateField(),
        ),
    ]
