# Generated by Django 2.2.6 on 2019-11-06 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0009_auto_20191024_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
