# Generated by Django 2.2.6 on 2019-11-17 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
#import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0010_auto_20191106_1632'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='idea',
        #     name='imagen',
        #     field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='imagenesIdeas/'),
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='imagen',
        #     field=models.ImageField(default='imagenesUsuarios/usuario.png', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='imagenesUsuarios/'),
        # ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('texto', models.CharField(max_length=100)),
                ('visto', models.BooleanField(default=False)),
                ('fecha_envio', models.DateField(auto_now_add=True)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notificacion',
            },
        ),
    ]
