# Generated by Django 2.2.6 on 2020-02-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0011_auto_20191117_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['monto_actual']},
        ),
    ]
